name: JavaScript Code Coverage Check

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests and coverage
        run: npm run test:coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: coverage

  coverage-check:
    runs-on: ubuntu-latest

    needs: test-and-coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: coverage

      - name: Check coverage threshold
        run: |
          COVERAGE_THRESHOLD=90  # Set your desired coverage threshold here
          COVERAGE=$(cat coverage/lcov-report/index.html | grep -oP '(?<=<span class="strong">)[0-9]+(?=%<\/span>)')
          echo "Coverage is $COVERAGE%"
          if [ "$COVERAGE" -lt "$COVERAGE_THRESHOLD" ]; then
            echo "Error: Coverage is below the threshold of $COVERAGE_THRESHOLD%"
            exit 1
          fi
